import { MD3LightTheme } from "react-native-paper";

export const colors = {
  paper: "#FFFFFF",
  paperDeep: "#EDF3E9",
  card: "#FFFFFF",
  surface: "#F7F9F5",
  surfaceRaised: "#FFFFFF",
  ink: "#1B211A",
  inkMuted: "#697267",
  forest: "#58764A",
  forestDark: "#31452B",
  forestSoft: "#E6EFE0",
  signal: "#DCEBCF",
  rust: "#BA4D46",
  rustSoft: "#F9E7E4",
  warning: "#8B6418",
  warningSoft: "#FFF1CF",
  rule: "#DCE4D8",
  white: "#FFFFFF",
  black: "#111410",
} as const;

export const typography = {
  display: "Manrope_700Bold",
  body: "Manrope_400Regular",
  medium: "Manrope_500Medium",
  label: "Manrope_600SemiBold",
  strong: "Manrope_700Bold",
  extraBold: "Manrope_800ExtraBold",
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
} as const;

export const radii = {
  md: 18,
  lg: 24,
  xl: 30,
  full: 999,
} as const;

const defaultFonts = MD3LightTheme.fonts;

export const paperTheme = {
  ...MD3LightTheme,
  version: 3 as const,
  roundness: 5,
  animation: { scale: 1 },
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.forest,
    onPrimary: colors.white,
    primaryContainer: colors.signal,
    onPrimaryContainer: colors.forestDark,
    secondary: "#687A5E",
    onSecondary: colors.white,
    secondaryContainer: colors.forestSoft,
    onSecondaryContainer: colors.forestDark,
    tertiary: "#7A6B45",
    onTertiary: colors.white,
    tertiaryContainer: "#F2E8C9",
    onTertiaryContainer: "#3E351E",
    error: colors.rust,
    errorContainer: colors.rustSoft,
    onErrorContainer: "#5E201C",
    background: colors.paper,
    onBackground: colors.ink,
    surface: colors.paper,
    onSurface: colors.ink,
    surfaceVariant: colors.surface,
    onSurfaceVariant: colors.inkMuted,
    outline: "#7A8577",
    outlineVariant: colors.rule,
    shadow: colors.black,
    scrim: colors.black,
    backdrop: "rgba(27, 33, 26, 0.42)",
    inverseSurface: colors.forestDark,
    inverseOnSurface: "#F2F6EF",
    inversePrimary: "#BED8AE",
    elevation: {
      level0: "transparent",
      level1: "#F7FAF5",
      level2: "#F2F7EF",
      level3: "#EDF4E9",
      level4: "#EAF2E6",
      level5: "#E6F0E2",
    },
  },
  fonts: {
    displayLarge: { ...defaultFonts.displayLarge, fontFamily: typography.extraBold },
    displayMedium: { ...defaultFonts.displayMedium, fontFamily: typography.extraBold },
    displaySmall: { ...defaultFonts.displaySmall, fontFamily: typography.display },
    headlineLarge: { ...defaultFonts.headlineLarge, fontFamily: typography.display },
    headlineMedium: { ...defaultFonts.headlineMedium, fontFamily: typography.display },
    headlineSmall: { ...defaultFonts.headlineSmall, fontFamily: typography.display },
    titleLarge: { ...defaultFonts.titleLarge, fontFamily: typography.strong },
    titleMedium: { ...defaultFonts.titleMedium, fontFamily: typography.label },
    titleSmall: { ...defaultFonts.titleSmall, fontFamily: typography.label },
    bodyLarge: { ...defaultFonts.bodyLarge, fontFamily: typography.body },
    bodyMedium: { ...defaultFonts.bodyMedium, fontFamily: typography.body },
    bodySmall: { ...defaultFonts.bodySmall, fontFamily: typography.body },
    labelLarge: { ...defaultFonts.labelLarge, fontFamily: typography.strong },
    labelMedium: { ...defaultFonts.labelMedium, fontFamily: typography.label },
    labelSmall: { ...defaultFonts.labelSmall, fontFamily: typography.label },
  },
};
